name: elementary_bloc_weather
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

dependencies:
  async: ^2.8.2
  bloc: ^8.0.2
  elementary: ^1.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  logger: ^1.1.0
  provider: ^6.0.1
  shimmer: ^2.0.0
  surf_logger: ^1.0.1
  yandex_mapkit: ^2.0.1
  geolocator: ^8.2.0
  http: ^0.13.4
  json_serializable: ^6.1.5
  
dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^4.7.0
  elementary_test: ^1.0.1
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.4.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  uses-material-design: true